architect:
  - vzurauskas
readers:
  - "urn:github:18754033"
assets:
  settings.xml: vzurauskas/secrets#nereides/settings.xml
  pubring.gpg: vzurauskas/secrets#pubring.gpg
  secring.gpg: vzurauskas/secrets#secring.gpg
merge:
  script: |
    mvn clean install -Pwall --errors
release:
  # https://github.com/vzurauskas/nereides-jackson/issues/29
  # mvn clean deploy nullfree:nullfree -Pwall -Pnereides -Prelease --errors --settings /home/r/settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pwall -Pnereides -Prelease --errors --settings /home/r/settings.xml